version: "2"
services:
  node:
    image: "node"
    user: "node"
    container_name: node-app
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "npm start"

